import Navbar from "@/components/ui/NavBar";
import "./globals.css";
import NavTop from "@/components/ui/NavTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden container" data-theme="cupcake"  cz-shortcut-listen="true">
        <div className="fixed right-0 min-h-screen min-w-screen container -z-20"></div>
        <NavTop/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
